### ISSUE TITLE
Meta: address all current `content: correction` issues

### ISSUE THREAD

**Issue by mechanomi** [crate/cloud-howtos#42]
this meta issue address all current `content: correction` issues

planned commits:

- [ ] Correction: Use HTTPS instead of HTTP for links (fixes https://github.com/crate/tech-writing-domain/issues/316)

- [ ] Improvement: Use shorter titles to improve search engine rankings (fixes https://github.com/crate/tech-writing-domain/issues/317)

**Comment by matthijskrul** [comment]
These are both done.
