### ISSUE TITLE
CrateDB Cloud backup policy

### ISSUE THREAD

**Issue by Taliik** [crate/cloud-howtos#43]
###  Documentation feedback
Backup policy:
Since the CrateDB Cloud Backup strategy has changed to `incremental backups`, we have more than the two weeks worth of data for the user to recover. The SLA guarantees the 14 days retention, but no data from the backups is deleted, so the second phrase `After that time snapshots will be deleted.` is wrong and should be removed.

 
- Page title: Restore backups and snapshots
- Page URL: https://crate.io/docs/cloud/howtos/en/latest/snapshot.html
- Source: https://github.com/crate/cloud-howtos/blob/master/docs/snapshot.rst

---

**Comment by matthijskrul** [comment]
Addressed by [this PR](https://github.com/crate/cloud-howtos/pull/45)
