### ISSUE TITLE
Metabase Community Tutorial

### ISSUE THREAD

**Issue by RomanMeingassner** [crate/cloud-howtos#72]
## Who
A metabase user

## What
To know how to connect CrateDB with Metabase

## Why
To use CrateDB with Metabase for data visualisation

----

## ACs

- [ ] A tutorial is written and published on the metabase community page
- [ ] Links from the tutorial are tracked (eg. with a referal param)

**Comment by matkuliak** [comment]
https://www.metabase.com/community_posts/real-time-data-analytics-with-metabase-and-cratedb
